package com.terning.domain.entity.response

data class RecommendInternModel(
    val internshipAnnouncementId: Long,
    val title: String,
    val dDay: String,
    val workingPeriod: String,
    val companyImage: String,
    val isScrapped: Boolean,
)
fun toRecommendInternEntity(): List<RecommendInternModel> =
    listOf(
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "ㅇㄻㅇㅁㄻㄹㅇㅁㅇㄹ",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = false,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = false,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = false,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = false,
        ),
        RecommendInternModel(
            internshipAnnouncementId = 1234123132,
            title = "[유한킴벌리] 그린캠프 w.대학생 숲 활동가",
            dDay = "D-2",
            workingPeriod = "4개월",
            companyImage = "https://reqres.in/img/faces/7-image.jpg",
            isScrapped = true,
        ),
    )
